# This is a basic workflow to help you get started with Actions

name: Fetch Data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OFAC.yaml'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  action-OFAC-sdnlist:
    runs-on: ubuntu-latest
    steps:
      - name: Get OFAC sdnlist.txt
        run: |
            curl https://www.treasury.gov/ofac/downloads/sdnlist.txt > sdnlist.txt
            cat sdnlist.txt
      - name: Parser blocklist to csv
        run: |
            cat sdnlist.txt \
            | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' \
            | sed 's/Digital Currency Address/\nDigital Currency Address/g' \
            | grep "Digital Currency Address" |sed -E 's/(Digital Currency Address - [A-Za-z0-9]+ [A-Za-z0-9]+) /\1/g' \
            | awk '{print $5,$6}' |sed -E 's/;|[\[\(].*//g' |sort -u |sed -E 's/ /,/g' \
            | sed 's/XBT/BTC/g' \
            | sed 's/USDT,0/ETH,0/g' \
            | sed -E 's/USDT/BTC/g' \
            | sed 's/ETC/ETH/g' > sdnlist.csv
            cat sdnlist.csv
      - name: Filter Coin
        run: |
            cat sdnlist.csv \
            | grep -v '^BTG' \
            | grep -v '^XMR' \
            | grep -v '^XVG' \
            | grep -v '^ZEC' > sdnlist.csv
            cat sdnlist.csv
      - name: Save to branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: ofac
